# Workflow to build installer on windows. Workflow runs when manually
# triggered using the UI or API.

name: Build Windows Installer for the Latest Release

on: workflow_dispatch

jobs:

  build-installer:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get latest release info
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Checkout released code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_release.outputs.tag_name }}

      - name: Build installer
        run: |
          cd tools\installer_building
          $build_out = .\build_windows_installer.ps1 ${{ steps.get_release.outputs.tag_name }}
          $build_time = Get-Date -format yyyyMMddHHmm
          $build_branch = echo $build_out|Select-String -Pattern "installed_version:"
          $build_branch = $build_branch.ToString().Substring(19)
          echo "build_id=$build_branch" >> ${env:GITHUB_ENV}
        shell: powershell

      - name: Upload installer artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: tools\installer_building\datalad-gooey-installer-amd64.exe
          asset_name: datalad-gooey-installer-${{ steps.get_release.outputs.tag_name }}-amd64.exe
          asset_content_type: application/vnd.microsoft.portable-executable
